// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class Address_setPostCode_2c27938152_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetPostCode() {
        String postCode = "12345";
        address.setPostCode(postCode);
        assertEquals(postCode, address.getPostCode());
    }

    @Test
    public void testSetEmptyPostCode() {
        String postCode = "";
        address.setPostCode(postCode);
        assertEquals(postCode, address.getPostCode());
    }
}
