// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Address_getPostCode_2164b971d2_Test {
    
    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testGetPostCode_whenPostCodeIsSet() {
        // TODO: Change the postcode value to a valid postcode
        String expectedPostCode = "12345";
        address.setPostCode(expectedPostCode);
        String actualPostCode = address.getPostCode();
        
        assertEquals(expectedPostCode, actualPostCode);
    }

    @Test
    public void testGetPostCode_whenPostCodeIsNotSet() {
        String actualPostCode = address.getPostCode();
        
        assertNull(actualPostCode);
    }
}
