// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import static org.junit.Assert.assertEquals;

public class Address_getNumber_321de2b906_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testGetNumber() {
        address.setNumber(123);
        assertEquals(123, address.getNumber());
    }

    @Test
    public void testGetNumberWhenNumberIsNegative() {
        address.setNumber(-123);
        assertEquals(-123, address.getNumber());
    }
}
