// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.Test;

public class Address_setNumber_c41e3ac58f_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetNumber_positive() {
        int expectedNumber = 123;
        address.setNumber(expectedNumber);
        assertEquals(expectedNumber, address.getNumber());
    }

    @Test
    public void testSetNumber_negative() {
        int expectedNumber = -123;
        address.setNumber(expectedNumber);
        assertEquals(expectedNumber, address.getNumber());
    }
}
