// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Address_getNumber_321de2b906_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testGetNumberSuccess() {
        int expectedNumber = 123;
        address.setNumber(expectedNumber);
        int actualNumber = address.getNumber();
        assertEquals(expectedNumber, actualNumber);
    }

    @Test
    public void testGetNumberDefault() {
        int expectedNumber = 0; // TODO: Change this value if the default value of number is changed in Address class
        int actualNumber = address.getNumber();
        assertEquals(expectedNumber, actualNumber);
    }
}
