// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.spockframework.runtime.extension.builtin.PreconditionContext;

import static org.junit.Assert.assertEquals;

public class Address_getStreet_1f4cbccdcf_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testGetStreet_Success() {
        String expectedStreet = "123 Main St";
        address.setStreet(expectedStreet);
        assertEquals("Test Case: testGetStreet_Success failed",
                expectedStreet, address.getStreet());
    }

    @Test
    public void testGetStreet_Null() {
        // TODO: Set the street to null
        address.setStreet(null);
        assertEquals("Test Case: testGetStreet_Null failed",
                null, address.getStreet());
    }
}
