// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Address_getPostCode_2164b971d2_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testGetPostCode() {
        String postCode = "12345";
        address.setPostCode(postCode);
        assertEquals(postCode, address.getPostCode());
    }

    @Test
    public void testGetPostCodeWhenNotSet() {
        assertNull(address.getPostCode());
    }
}
