// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class Address_getCountry_60edba3cae_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testGetCountry() {
        String country = "USA";
        address.setCountry(country);

        String result = address.getCountry();

        assertEquals("Country should be USA", country, result);
    }

    @Test
    public void testGetCountryWhenCountryIsNull() {
        address.setCountry(null);

        String result = address.getCountry();

        assertEquals("Country should be null", null, result);
    }
}
