// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Address_setPostCode_2c27938152_Test {

    private Address address;

    @BeforeEach
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetPostCode() {
        String postCode = "12345";
        address.setPostCode(postCode);
        assertEquals(postCode, address.getPostCode());
    }

    @Test
    public void testSetPostCodeWithNull() {
        assertThrows(NullPointerException.class, () -> address.setPostCode(null));
    }

    @Test
    public void testSetPostCodeWithEmptyString() {
        String postCode = "";
        address.setPostCode(postCode);
        assertEquals(postCode, address.getPostCode());
    }
}
