// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import org.junit.Assert;
import org.spockframework.util.Assert;

public class Address_setStreet_e6ff69dda3_Test {

    @Test
    public void testSetStreet() {
        Address address = new Address();
        address.setStreet("123 Main St");
        Assert.assertEquals("123 Main St", address.getStreet());
    }

    @Test
    public void testSetStreetWithNull() {
        Address address = new Address();
        address.setStreet(null);
        Assert.assertNull(address.getStreet());
    }
}
