// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.*;

public class Address_setNumber_c41e3ac58f_Test {

    @Test
    public void testSetNumberPositive() {
        Address address = new Address();
        int expectedNumber = 123;
        address.setNumber(expectedNumber);
        assertEquals(expectedNumber, address.getNumber());
    }

    @Test
    public void testSetNumberNegative() {
        Address address = new Address();
        int expectedNumber = -456;
        address.setNumber(expectedNumber);
        assertEquals(expectedNumber, address.getNumber());
    }

    @Test(expected = NumberFormatException.class)
    public void testSetNumberException() {
        Address address = new Address();
        int number = Integer.parseInt("not a number");
        address.setNumber(number);
    }
}
