// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Address_setCountry_ba4f129349_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetCountry() {
        String testCountry = "USA";
        address.setCountry(testCountry);
        assertEquals("Country should be set to USA", testCountry, address.getCountry());
    }

    @Test
    public void testSetCountryNull() {
        address.setCountry(null);
        assertNull("Country should be null", address.getCountry());
    }
}
