// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class Address_setCountry_ba4f129349_Test {
    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetCountry() {
        String country = "USA";
        address.setCountry(country);
        assertEquals("Country should be set to USA", country, address.getCountry());
    }

    @Test
    public void testSetCountryWithEmptyString() {
        String country = "";
        address.setCountry(country);
        assertEquals("Country should be set to an empty string", country, address.getCountry());
    }
}
