// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.Test;

public class Address_setStreet_e6ff69dda3_Test {

    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetStreet() {
        String expectedStreet = "123 Main St";
        address.setStreet(expectedStreet);
        assertEquals(expectedStreet, address.getStreet());
    }

    @Test
    public void testSetStreetNull() {
        address.setStreet(null);
        assertEquals(null, address.getStreet());
    }
}
