// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Address_setNumber_c41e3ac58f_Test {
    
    private Address address;
    
    @BeforeEach
    public void setup() {
        address = new Address();
    }
    
    @Test
    public void testSetNumber_PositiveNumber() {
        address.setNumber(100);
        assertEquals(100, address.getNumber());
    }
    
    @Test
    public void testSetNumber_NegativeNumber() {
        address.setNumber(-100);
        assertEquals(-100, address.getNumber());
    }
}
