// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class Address_getNumber_321de2b906_Test {

    private final Address address = new Address();

    @Test
    public void testGetNumberWhenNumberIsSet() {
        int expectedNumber = 123;
        address.setNumber(expectedNumber);
        int actualNumber = address.getNumber();

        assertEquals("Number should be " + expectedNumber, expectedNumber, actualNumber);
    }

    @Test
    public void testGetNumberWhenNumberIsNotSet() {
        int defaultNumber = 0;
        int actualNumber = address.getNumber();

        assertEquals("Number should be " + defaultNumber, defaultNumber, actualNumber);
    }
}
