// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_setInTraining_3e92e5e332_Test {

    @Test
    public void testSetInTrainingTrue() {
        Employee employee = new Employee();
        employee.setInTraining(true);
        assertTrue(employee.isInTraining());
    }

    @Test
    public void testSetInTrainingFalse() {
        Employee employee = new Employee();
        employee.setInTraining(false);
        assertFalse(employee.isInTraining());
    }
}
