// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.spockframework.mock.MockImplementation;

public class Employee_getMiddleName_e4a286331a_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testGetMiddleNameWhenMiddleNameIsNull() {
        employee.setMiddleName(null);
        String middleName = employee.getMiddleName();
        Assert.assertNull(middleName);
    }

    @Test
    public void testGetMiddleNameWhenMiddleNameIsNotEmpty() {
        String expectedMiddleName = "John";
        employee.setMiddleName(expectedMiddleName);
        String actualMiddleName = employee.getMiddleName();
        Assert.assertEquals(expectedMiddleName, actualMiddleName);
    }
}
