// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_setLastName_4141db5e7c_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testSetLastName() {
        String lastName = "Smith";
        employee.setLastName(lastName);
        assertEquals("The last name should be Smith", lastName, employee.getLastName());
    }

    @Test
    public void testSetLastNameWithNull() {
        employee.setLastName(null);
        assertNull("The last name should be null", employee.getLastName());
    }

    // TODO: Add more test cases if needed.
}
