// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_setRetired_82800f4e10_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testSetRetired_true() {
        employee.setRetired(true);
        assertTrue(employee.isRetired());
    }

    @Test
    public void testSetRetired_false() {
        employee.setRetired(false);
        assertFalse(employee.isRetired());
    }
}
