// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import static org.junit.Assert.assertEquals;

public class Employee_isInTraining_21034345c6_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testIsInTrainingTrue() {
        employee.setInTraining(true);
        assertEquals(true, employee.isInTraining());
    }

    @Test
    public void testIsInTrainingFalse() {
        employee.setInTraining(false);
        assertEquals(false, employee.isInTraining());
    }
}
