// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Employee_isInTraining_21034345c6_Test {

    @Mock
    Employee employee;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsInTraining_True() {
        when(employee.isInTraining()).thenReturn(true);

        boolean inTraining = employee.isInTraining();

        Assert.assertTrue(inTraining);
    }

    @Test
    public void testIsInTraining_False() {
        when(employee.isInTraining()).thenReturn(false);

        boolean inTraining = employee.isInTraining();

        Assert.assertFalse(inTraining);
    }
}
