// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Test;

public class Employee_getFirstName_94e06d272a_Test {

    @Test
    public void testGetFirstName() {
        Employee employee = new Employee();
        employee.setFirstName("John");
        Assert.assertEquals("John", employee.getFirstName());
    }

    @Test
    public void testGetFirstNameWithNull() {
        Employee employee = new Employee();
        employee.setFirstName(null);
        Assert.assertNull(employee.getFirstName());
    }
}
