// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import org.spockframework.util.Assert;
import Employee;

public class Employee_setFirstName_8acaec2cfc_Test {

    @Test
    public void testSetFirstNameSuccess() {
        Employee employee = new Employee();
        employee.setFirstName("John");
        Assert.notNull(employee.getFirstName(), "First name should not be null");
        Assert.equals(employee.getFirstName(), "John", "First name should be John");
    }

    @Test
    public void testSetFirstNameNull() {
        Employee employee = new Employee();
        employee.setFirstName(null);
        Assert.isNull(employee.getFirstName(), "First name should be null");
    }

}
