// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.spockframework.mock.MockImplementation;
import org.spockframework.mock.MockNature;

public class Employee_isInTraining_21034345c6_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testIsInTrainingWhenTrue() {
        employee.setInTraining(true);
        Assert.assertTrue("The employee should be in training", employee.isInTraining());
    }

    @Test
    public void testIsInTrainingWhenFalse() {
        employee.setInTraining(false);
        Assert.assertFalse("The employee should not be in training", employee.isInTraining());
    }
}
