// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import org.spockframework.runtime.model.SpecMetadata;
import spock.lang.Specification;
import spock.lang.Subject;

import static org.junit.Assert.assertEquals;

@RunWith(SpockRunner.class)
@SpecMetadata(filename = "Employee_getAge_4fc4faa7b8_Test.groovy", line = 1)
public class Employee_getAge_4fc4faa7b8_Test extends Specification {

    @Subject
    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testGetAge() {
        employee.setAge(25);
        int expectedAge = 25;
        assertEquals(expectedAge, employee.getAge());
    }

    @Test
    public void testGetAgeWithZero() {
        employee.setAge(0);
        int expectedAge = 0;
        assertEquals(expectedAge, employee.getAge());
    }

}
