// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.spockframework.mock.MockImplementation;
import org.spockframework.mock.MockUtil;
import org.spockframework.runtime.InvalidSpecException;

public class Employee_isRetired_a47d9261b8_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testIsRetired_WhenEmployeeIsRetired() {
        employee.setRetired(true);
        Assert.assertTrue(employee.isRetired());
    }

    @Test
    public void testIsRetired_WhenEmployeeIsNotRetired() {
        employee.setRetired(false);
        Assert.assertFalse(employee.isRetired());
    }
} 
