// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_getMiddleName_e4a286331a_Test {

    @Test
    public void testGetMiddleName() {
        Employee employee = new Employee();
        employee.setMiddleName("John");
        assertEquals("John", employee.getMiddleName());
    }

    @Test
    public void testGetMiddleName_Null() {
        Employee employee = new Employee();
        assertNull(employee.getMiddleName());
    }
}
