// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Employee_getLastName_4814a2dee7_Test {

    @Mock
    Employee employee;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetLastName() {
        String expectedLastName = "Smith";
        Mockito.when(employee.getLastName()).thenReturn(expectedLastName);
        String actualLastName = employee.getLastName();
        Assert.assertEquals(expectedLastName, actualLastName);
    }

    @Test
    public void testGetLastName_Null() {
        String expectedLastName = null;
        Mockito.when(employee.getLastName()).thenReturn(expectedLastName);
        String actualLastName = employee.getLastName();
        Assert.assertNull(actualLastName);
    }
}
