// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import org.spockframework.runtime.model.SpecMetadata;
import org.spockframework.runtime.runner.SpockRunner;
import org.spockframework.util.Assert;
import static org.junit.Assert.*;

@RunWith(SpockRunner.class)
@SpecMetadata(filename = "Employee_setAge_d18d9b25c4_Test.groovy", line = 1)
public class Employee_setAge_d18d9b25c4_Test {

    Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testSetAge_ValidAge() {
        employee.setAge(30);
        assertEquals(30, employee.getAge());
    }

    @Test
    public void testSetAge_InvalidAge() {
        try {
            employee.setAge(-1);
        } catch (IllegalArgumentException e) {
            assertNotNull(e.getMessage());
        }
    }

}
