// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import org.spockframework.runtime.model.SpecMetadata;
import org.spockframework.runtime.model.FeatureMetadata;
import spock.lang.Specification;
import spock.lang.Subject;
import org.spockframework.runtime.SpockRuntime;

@RunWith(SpockRuntime.class)
@SpecMetadata(filename = "Employee_setAge_d18d9b25c4_Test.groovy", line = 1)
public class Employee_setAge_d18d9b25c4_Test extends Specification {

    @Subject
    private Employee employee = new Employee();

    @FeatureMetadata(name = "setAge", line = 6, description = "Test the setAge method")
    public void testSetAge() {
        when: "age is set"
        employee.setAge(30);
        
        then: "age should be set correctly"
        assert employee.getAge() == 30;
    }

    @FeatureMetadata(name = "setAge", line = 13, description = "Test the setAge method with negative age")
    public void testSetAgeNegative() {
        when: "negative age is set"
        employee.setAge(-5);

        then: "age should be set correctly"
        assert employee.getAge() == -5;
    }
}
