// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Test;

public class Employee_setInTraining_3e92e5e332_Test {

    @Test
    public void testSetInTraining_True() {
        Employee employee = new Employee();
        employee.setInTraining(true);
        Assert.assertTrue(employee.isInTraining());
    }

    @Test
    public void testSetInTraining_False() {
        Employee employee = new Employee();
        employee.setInTraining(false);
        Assert.assertFalse(employee.isInTraining());
    }
}
