// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_getLastName_4814a2dee7_Test {

    @Test
    public void testGetLastName() {
        // TODO: Initialise the Employee object with a last name
        Employee employee = new Employee();
        employee.setLastName("Smith");
        String lastName = employee.getLastName();
        assertEquals("Smith", lastName);
    }

    @Test
    public void testGetLastNameWithNull() {
        // TODO: Initialise the Employee object without a last name
        Employee employee = new Employee();
        String lastName = employee.getLastName();
        assertNull(lastName);
    }
}
