// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.spockframework.mock.MockUtil;

public class Employee_setLastName_4141db5e7c_Test {
    Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testSetLastName() {
        String expectedLastName = "Smith";
        employee.setLastName(expectedLastName);
        Assert.assertEquals("Employee's last name should be Smith", expectedLastName, employee.getLastName());
    }

    @Test
    public void testSetLastName_Null() {
        String expectedLastName = null;
        employee.setLastName(expectedLastName);
        Assert.assertNull("Employee's last name should be null", employee.getLastName());
    }
}
