// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class Employee_getLastName_4814a2dee7_Test {

    private Employee employee;

    @Before
    public void setup() {
        employee = new Employee();
    }

    @Test
    public void testGetLastName() {
        employee.setLastName("Smith");
        String actual = employee.getLastName();
        Assert.assertEquals("Smith", actual);
    }

    @Test
    public void testGetLastName_Null() {
        employee.setLastName(null);
        String actual = employee.getLastName();
        Assert.assertNull(actual);
    }
}
