// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.SpockRunner;

@RunWith(SpockRunner.class)
public class Employee_setInTraining_3e92e5e332_Test {
    private Employee employee;

    @Before
    public void setup() {
        employee = new Employee();
    }

    @Test
    public void testSetInTraining_True() {
        employee.setInTraining(true);
        Assert.assertTrue(employee.isInTraining());
    }

    @Test
    public void testSetInTraining_False() {
        employee.setInTraining(false);
        Assert.assertFalse(employee.isInTraining());
    }
}
