// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.spockframework.lang.Wildcard;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import org.spockframework.util.Assert;
import spock.lang.Specification;

public class Employee_setFirstName_8acaec2cfc_Test extends Specification {

    private Employee employee;

    @Before
    public void setup() {
        employee = new Employee();
    }
    
    // Test case when firstName is a valid string
    public void testSetFirstNameValid() {
        String validFirstName = "John";
        employee.setFirstName(validFirstName);
        Assert.that(employee.getFirstName(), is(validFirstName));
    }
    
    // Test case when firstName is null
    public void testSetFirstNameNull() {
        String nullFirstName = null;
        employee.setFirstName(nullFirstName);
        Assert.that(employee.getFirstName(), is(nullFirstName));
    }
}
