// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import org.spockframework.mock.MockUtil;

public class Employee_setMiddleName_f0344a6fb8_Test {

    private Employee employee;
    private MockUtil mockUtil;

    @Before
    public void setUp() {
        employee = new Employee();
        mockUtil = new MockUtil();
    }

    @Test
    public void testSetMiddleName() {
        String expectedMiddleName = "Michael";
        employee.setMiddleName(expectedMiddleName);

        assertEquals(expectedMiddleName, employee.getMiddleName());
    }

    @Test
    public void testSetMiddleName_NullValue() {
        employee.setMiddleName(null);

        assertNull(employee.getMiddleName());
    }

    @Test
    public void testSetMiddleName_EmptyString() {
        employee.setMiddleName("");

        assertEquals("", employee.getMiddleName());
    }
}
