// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class Employee_isRetired_a47d9261b8_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = mock(Employee.class);
    }

    @Test
    public void testIsRetired_true() {
        when(employee.isRetired()).thenReturn(true);
        assertTrue(employee.isRetired());
    }

    @Test
    public void testIsRetired_false() {
        when(employee.isRetired()).thenReturn(false);
        assertFalse(employee.isRetired());
    }
}
