// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.extension.IMethodInterceptor;
import org.spockframework.runtime.extension.IMethodInvocation;
import org.spockframework.runtime.model.SpecInfo;
import spock.lang.Specification;
import spock.lang.Stepwise;

import static org.junit.Assert.assertEquals;

@RunWith(SpockRunner.class)
@Stepwise
public class Employee_setFirstName_8acaec2cfc_Test extends Specification implements IMethodInterceptor {

    private Employee employee = new Employee();

    @Override
    public void intercept(IMethodInvocation invocation) throws Throwable {
        invocation.proceed();
    }

    @Override
    public void visitSpec(SpecInfo spec) {
        spec.getAllFeatures().stream().forEach(feature -> {
            feature.getFeatureMethod().addInterceptor(this);
        });
    }

    @Test
    public void testSetFirstName() {
        employee.setFirstName("John");
        assertEquals("John", employee.getFirstName());
    }

    @Test
    public void testSetFirstNameWithNull() {
        employee.setFirstName(null);
        assertEquals(null, employee.getFirstName());
    }
}
