// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class Employee_getFirstName_94e06d272a_Test {

    private Employee employee;

    @Before
    public void setUp() {
        employee = new Employee();
    }

    @Test
    public void testGetFirstName_WithValidName() {
        String expectedFirstName = "John";
        employee.setFirstName(expectedFirstName);
        String actualFirstName = employee.getFirstName();
        Assert.assertEquals(expectedFirstName, actualFirstName);
    }

    @Test
    public void testGetFirstName_WithNull() {
        employee.setFirstName(null);
        String actualFirstName = employee.getFirstName();
        Assert.assertNull(actualFirstName);
    }
}
