// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.spockframework.runtime.extension.AbstractAnnotationDrivenExtension;
import static org.junit.Assert.assertEquals;

public class Employee_getAge_4fc4faa7b8_Test {

    Employee employee;
  
    @Before
    public void setup() {
        employee = new Employee();
        employee.setAge(30); // TODO: Change the value as per requirement
    }
  
    @Test
    public void testGetAge_PositiveCase() {
        int expectedAge = 30; // TODO: Change the value as per requirement
        int actualAge = employee.getAge();
        assertEquals(expectedAge, actualAge);
    }
  
    @Test
    public void testGetAge_EdgeCase() {
        employee.setAge(Integer.MAX_VALUE);
        int expectedAge = Integer.MAX_VALUE;
        int actualAge = employee.getAge();
        assertEquals(expectedAge, actualAge);
    }
  
}
