// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_setMiddleName_f0344a6fb8_Test {

    @Test
    public void testSetMiddleName() {
        Employee employee = new Employee();

        // Test with valid middle name
        String validMiddleName = "John";
        employee.setMiddleName(validMiddleName);
        assertEquals(validMiddleName, employee.getMiddleName());

        // Test with null middle name
        String nullMiddleName = null;
        employee.setMiddleName(nullMiddleName);
        assertNull(employee.getMiddleName());

        // Test with empty middle name
        String emptyMiddleName = "";
        employee.setMiddleName(emptyMiddleName);
        assertEquals(emptyMiddleName, employee.getMiddleName());
    }
}
