// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Test;

public class Employee_isRetired_a47d9261b8_Test {

    @Test
    public void testIsRetired() {
        Employee employee = new Employee();
        employee.setRetired(true);
        Assert.assertTrue("Employee should be retired", employee.isRetired());
    }

    @Test
    public void testIsNotRetired() {
        Employee employee = new Employee();
        employee.setRetired(false);
        Assert.assertFalse("Employee should not be retired", employee.isRetired());
    }
}
