// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.spockframework.runtime.extension.MethodInterceptor;
import org.spockframework.runtime.extension.IMethodInvocation;

public class Employee_setRetired_82800f4e10_Test {

    private Employee employee;

    @Before
    public void setup() {
        employee = new Employee();
    }

    @Test
    public void testSetRetiredTrue() {
        employee.setRetired(true);
        Assert.assertTrue(employee.isRetired());
    }

    @Test
    public void testSetRetiredFalse() {
        employee.setRetired(false);
        Assert.assertFalse(employee.isRetired());
    }
}
