// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import static org.junit.Assert.*;

public class Employee_setMiddleName_f0344a6fb8_Test {

    @Test
    public void testSetMiddleName() {
        Employee employee = new Employee();
        String middleName = "John";
        employee.setMiddleName(middleName);
        assertEquals(middleName, employee.getMiddleName());
    }

    @Test
    public void testSetMiddleNameWithNull() {
        Employee employee = new Employee();
        employee.setMiddleName(null);
        assertNull(employee.getMiddleName());
    }
}
