// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Test;

public class Employee_getMiddleName_e4a286331a_Test {
    
    @Test
    public void testGetMiddleName() {
        Employee employee = new Employee();
        employee.setMiddleName("Michael");
        String middleName = employee.getMiddleName();
        Assert.assertEquals("Michael", middleName);
    }
    
    @Test
    public void testGetMiddleName_Null() {
        Employee employee = new Employee();
        String middleName = employee.getMiddleName();
        Assert.assertNull(middleName);
    }
}
