// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Test;

public class Employee_getAge_4fc4faa7b8_Test {

    @Test
    public void testGetAge() {
        Employee employee = new Employee();
        employee.setAge(30);
        Assert.assertEquals(30, employee.getAge());
    }

    @Test
    public void testGetAgeWithNull() {
        Employee employee = new Employee();
        employee.setAge(null);
        Assert.assertNull(employee.getAge());
    }
}
