// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class MilitaryPerson_getFirstName_94e06d272a_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testGetFirstName_whenFirstNameIsSet() {
        String expectedFirstName = "John";
        
        // TODO: Set the firstName field of the militaryPerson object to "John"
        militaryPerson.setFirstName(expectedFirstName);
        
        Assert.assertEquals(expectedFirstName, militaryPerson.getFirstName());
    }

    @Test
    public void testGetFirstName_whenFirstNameIsNotSet() {
        Assert.assertNull(militaryPerson.getFirstName());
    }
}
