// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Test;
import org.spockframework.runtime.extension.IMethodInterceptor;
import org.spockframework.runtime.extension.IMethodInvocation;
import org.spockframework.runtime.model.FieldInfo;
import org.spockframework.runtime.model.SpecInfo;

public class MilitaryPerson_getLastName_4814a2dee7_Test {
    private MilitaryPerson militaryPerson;

    @Before
    public void setup() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testGetLastName() {
        militaryPerson.setLastName("Smith");
        assertEquals("Smith", militaryPerson.getLastName());
    }

    @Test
    public void testGetLastName_Null() {
        militaryPerson.setLastName(null);
        assertNull(militaryPerson.getLastName());
    }
}
