// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class MilitaryPerson_getLastName_4814a2dee7_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testGetLastNameSuccess() {
        String expectedLastName = "Doe";
        militaryPerson.setLastName(expectedLastName);
        String actualLastName = militaryPerson.getLastName();
        Assert.assertEquals(expectedLastName, actualLastName);
    }

    @Test
    public void testGetLastNameNull() {
        militaryPerson.setLastName(null);
        String actualLastName = militaryPerson.getLastName();
        Assert.assertNull(actualLastName);
    }
}
