// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.spockframework.runtime.extension.builtin.PreconditionContext;
import static org.junit.Assert.*;

public class MilitaryPerson_setLastName_4141db5e7c_Test {
    
    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testSetLastName() {
        String expectedLastName = "Smith";
        militaryPerson.setLastName(expectedLastName);
        assertEquals(expectedLastName, militaryPerson.getLastName());
    }

    @Test
    public void testSetLastNameNull() {
        String expectedLastName = null;
        militaryPerson.setLastName(expectedLastName);
        assertEquals(expectedLastName, militaryPerson.getLastName());
    }
}
