// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class MilitaryPerson_getFirstName_94e06d272a_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testGetFirstName_whenFirstNameIsSet() {
        String expectedFirstName = "John";
        militaryPerson.setFirstName(expectedFirstName);
        assertEquals(expectedFirstName, militaryPerson.getFirstName());
    }

    @Test
    public void testGetFirstName_whenFirstNameIsNotSet() {
        assertNull(militaryPerson.getFirstName());
    }
}
