// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.extension.IGlobalExtension;
import org.spockframework.runtime.model.SpecInfo;
import static org.junit.Assert.*;

@RunWith(SpockRunner.class)
public class MilitaryPerson_getRank_20c8177564_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testGetRank() {
        militaryPerson.setRank("General");
        String rank = militaryPerson.getRank();
        assertNotNull(rank);
        assertEquals("General", rank);
    }

    @Test
    public void testGetRankWhenRankNotSet() {
        String rank = militaryPerson.getRank();
        assertNull(rank);
    }
}
