// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class MilitaryPerson_setLastName_4141db5e7c_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testSetLastName() {
        String expectedLastName = "Smith";
        militaryPerson.setLastName(expectedLastName);
        Assert.assertEquals(expectedLastName, militaryPerson.getLastName());
    }

    @Test
    public void testSetLastName_NullValue() {
        try {
            militaryPerson.setLastName(null);
            Assert.fail("Expected an IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException e) {
            Assert.assertEquals("Last name cannot be null", e.getMessage());
        }
    }
}
