// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.spockframework.lang.Wildcard;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;

public class MilitaryPerson_getRank_20c8177564_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() throws Exception {
        militaryPerson = mock(MilitaryPerson.class);
    }

    @Test
    public void testGetRank_Success() {
        when(militaryPerson.getRank()).thenReturn("General");
        String rank = militaryPerson.getRank();
        assertEquals("General", rank);
    }

    @Test
    public void testGetRank_Failure() {
        when(militaryPerson.getRank()).thenReturn("General");
        String rank = militaryPerson.getRank();
        assertNotEquals("Captain", rank);
    }
}
