// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class MilitaryPerson_setFirstName_8acaec2cfc_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testSetFirstNameSuccess() {
        String expectedFirstName = "John";
        militaryPerson.setFirstName(expectedFirstName);
        assertEquals(expectedFirstName, militaryPerson.getFirstName());
    }

    @Test
    public void testSetFirstNameNull() {
        militaryPerson.setFirstName(null);
        assertNull(militaryPerson.getFirstName());
    }
}
