// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.spockframework.runtime.extension.ExtensionException;
import org.spockframework.runtime.model.FieldInfo;
import org.spockframework.runtime.model.SpecInfo;

@RunWith(SpockRunner.class)
public class MilitaryPerson_setFirstName_8acaec2cfc_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setup() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testSetFirstName_ValidName() {
        String validName = "John";
        militaryPerson.setFirstName(validName);

        FieldInfo field = SpecInfo.getFromObject(militaryPerson).getField("firstName");
        String actualName = (String) field.readValue(militaryPerson);

        assert validName.equals(actualName);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSetFirstName_NullName() {
        militaryPerson.setFirstName(null);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSetFirstName_EmptyName() {
        militaryPerson.setFirstName("");
    }

}
