// Test generated by RoostGPT for test SpockTest using AI Type Open AI and AI Model gpt-4

package com.manning.spock.chapter2;

import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.Test;

public class MilitaryPerson_getFirstName_94e06d272a_Test {

    private MilitaryPerson militaryPerson;

    @Before
    public void setUp() {
        militaryPerson = new MilitaryPerson();
    }

    @Test
    public void testGetFirstName_WhenNameIsJohn() {
        militaryPerson.setFirstName("John");
        String expected = "John";
        String actual = militaryPerson.getFirstName();
        assertEquals(expected, actual);
    }
    
    @Test
    public void testGetFirstName_WhenNameIsEmpty() {
        militaryPerson.setFirstName("");
        String expected = "";
        String actual = militaryPerson.getFirstName();
        assertEquals(expected, actual);
    }
}
